languageCode = "en"
languageName = "English"
weight = 1
title = "Ehsan's Blog"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Sharing knowledge, stories, and experiences â€” because learning is more fun together."

[params.author]
  name = "Ehsan Malik"
  image = "img/avatar.png"
  headline = "Full Stack / Magician"
  bio = "ğŸ‘‰Cheerful coder & open-source enthusiast.ğŸ§"
  links = [
    { email = "mailto:em1130mail@gmail.com" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]