languageCode = "zh-cn"
languageName = "ç®€ä½“ä¸­æ–‡"
weight = 4
title = "Ehsan çš„åšå®¢"

[params]
  displayName = "ç®€ä½“ä¸­æ–‡"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  description = "åˆ†äº«çŸ¥è¯†ã€æ•…äº‹å’Œç»éªŒï¼Œå› ä¸ºä¸€èµ·å­¦ä¹ æ›´æœ‰è¶£ã€‚"

[params.author]
  name = "Ehsan Malik"
  image = "img/avatar.png"
  headline = "å…¨æ ˆ / é­”æœ¯å¸ˆ"
  bio = "å¼€æœ—çš„å¼€å‘è€… ğŸ’» Â· å¼€æºçˆ±å¥½è€… ğŸ§ Â· å™äº‹å‘å•æœºæ¸¸æˆçˆ±å¥½è€… ğŸ®"
  links = [
    { email = "mailto:em1130mail@gmail.com" },
    { github = "https://github.com/KingTom871" },
  ]